secretsprovider: azurekeyvault://moi-key-vault.vault.azure.net/keys/pulumi-secret
encryptedkey: d29JZGpLNDREWDkyNEtGZDlha1JvMlBhQnYtaFBLVXVWX2xJTi1ONDVFYkY4dUxyU1JlT0dweWkydDliYXdwZE9lOXEyc2VlMUNRN083YkIwbWpjb3BiczZfUzJPeHprNVVxTGtaRHBpaGhFWWdLQXA4TzQwdkFqMFNKekRXMFhyVVN2UEMwenBkREwzX3liM1k1eDVHSDZVQkJJNkR0OGtWSXNLWEprN0pXV3NhNlNRdlNnMFo5X3dQZ1BoVFloakdSTkRQZkRyUnZRRllwT2RwazZEM3lrVC1JMDRsSDJEcU5LWkxrUHpwRUFSN19xSXNONzFHMzVKSVdjRlhCb3FtZEYxZGFMSkRDMVZ2d040SzY4R3VhT1pvYjJjTjlySTlDcGhKNEFRQUh3U2dBTG5FV2dmVmt0N1MwVlRKQUMyb0dZSXpRa3ZROTBlT3RfQWJuZ0VR
config:
  azure:location: norwayeast
